### ISSUE TITLE
Error with headless auth

### ISSUE THREAD

**Issue by kaiomagalhaes** [AzureAD/azure-activedirectory-library-for-ruby#40]
On the last example: /samples/user_credentials_example

I have updated the client Id and tenant, but I'm getting the following error:
```
$ ruby microsoft-test-headless.rb 
Username: kaiocodelitt@hotmail.com
Password: myPassword
V, [2016-02-29T15:43:25.147883 #6749] VERBOSE -- 0b3fa870-c4eb-4a86-81e0-6b62309eb299: TokenRequest getting token with user credential UserCredential[Username: kaiocodelitt@hotmail.com, AccountType: Federated] and resource https://graph.windows.net.
V, [2016-02-29T15:43:25.148092 #6749] VERBOSE -- 0b3fa870-c4eb-4a86-81e0-6b62309eb299: Getting OAuth parameters for Federated kaiocodelitt@hotmail.com.
/home/kaio/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http/generic_request.rb:25:in `initialize': HTTP request path is empty (ArgumentError)
	from /home/kaio/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http/request.rb:14:in `initialize'
	from /home/kaio/.rvm/gems/ruby-2.2.3/gems/adal-1.0.0/lib/adal/mex_request.rb:47:in `new'
	from /home/kaio/.rvm/gems/ruby-2.2.3/gems/adal-1.0.0/lib/adal/mex_request.rb:47:in `execute'
	from /home/kaio/.rvm/gems/ruby-2.2.3/gems/adal-1.0.0/lib/adal/user_credential.rb:143:in `mex_response'
	from /home/kaio/.rvm/gems/ruby-2.2.3/gems/adal-1.0.0/lib/adal/user_credential.rb:149:in `wstrust_request'
	from /home/kaio/.rvm/gems/ruby-2.2.3/gems/adal-1.0.0/lib/adal/user_credential.rb:121:in `federated_request_params'
	from /home/kaio/.rvm/gems/ruby-2.2.3/gems/adal-1.0.0/lib/adal/user_credential.rb:88:in `request_params'
	from /home/kaio/.rvm/gems/ruby-2.2.3/gems/adal-1.0.0/lib/adal/token_request.rb:147:in `get_with_user_credential'
	from /home/kaio/.rvm/gems/ruby-2.2.3/gems/adal-1.0.0/lib/adal/authentication_context.rb:150:in `acquire_token_for_user'
```
Does anyone know how to fix it?

**Comment by vibronet** [comment]
Direct use of username and password doesn't work for MSA accounts. That is by design. See http://www.cloudidentity.com/blog/2014/07/08/using-adal-net-to-authenticate-users-via-usernamepassword/, it holds for all flavors of ADAL as it depends on the behavior of the azure ad endpoints.
